###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

routes:

  # SIMPLE ROUTE EXAMPLE
  # Visiting example.com/contact-us will...
  # load the /templates/contact.html template

  /sitemap:
      layout: sitemap

  # ADVANCED ROUTE EXAMPLE
  # Visiting example.com/members/login will...
  # load the /templates/success.html template
  # and use the /layouts/system.html layout

  # /members/login:
    # template: success
    # layout: system

ignore:
  # - success
